name: Build Packer Image

on:
  push:
    branches:
      - main  # Runs only when PR is merged

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

  packer-build:
    name: Build Packer Image (AWS & GCP)
    needs: build-and-test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # provider: [aws, gcp]
        provider: [gcp]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Packer
        uses: hashicorp/setup-packer@main

      - name: Set up GCP credentials
        run: |
          echo "$GCP_SA_KEY" > gcp-key.json
          export GOOGLE_APPLICATION_CREDENTIALS=gcp-key.json
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}

      - name: Build Packer Image
        run: |
          packer init ./packer
          packer fmt ./packer
          packer validate -var-file=packer/values.pkrvars.hcl ./packer
          packer build -var-file=packer/values.pkrvars.hcl -only=googlecompute.ubuntu -var